name = "Pengdoll World"
author = "chanh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "76c7b4393a5db0e1c59f3ce71a83b2440e1a25797cb15f321d1e427b7850f1a1"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
