name = "Pengdoll World"
author = "chanh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54169c867a85603438229e1a13064ed9169c60e176e80b6a4c0a3be2f3afca35"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
