name = "Pengdoll World"
author = "chanh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3bf79d1a6a2ff1fa8ccfb965b6811580e119607bcf1b61abb3aef71e3271c372"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
